"""empty message

Revision ID: d4f4c5a61bcf
Revises: 43b3804abba4
Create Date: 2025-04-12 22:33:30.167063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f4c5a61bcf'
down_revision: Union[str, None] = '43b3804abba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('winner_1', sa.String(), nullable=False),
    sa.Column('winner_2', sa.String(), nullable=False),
    sa.Column('winner_3', sa.String(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('anons', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_column('anons', 'is_finished')
    op.drop_table('results')
    # ### end Alembic commands ###
